# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chem_ID', models.TextField()),
                ('Name', models.TextField()),
                ('Date', models.TextField()),
                ('PMID', models.TextField()),
                ('Properties', models.TextField()),
                ('Type', models.TextField()),
                ('Effect_to_PrP', models.TextField()),
                ('Effect_to_Diseases_progression', models.TextField()),
                ('Materials', models.TextField()),
                ('Information_of_Materials', models.TextField()),
                ('Treatement', models.TextField()),
                ('Binding_site', models.TextField()),
                ('PubChem', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chem_ID', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('Date', models.TextField(max_length=11)),
                ('PMID', models.TextField(max_length=20)),
                ('Properties', models.TextField(max_length=50)),
                ('Type', models.TextField(max_length=50)),
                ('Effect_to_PrP', models.TextField(max_length=50)),
                ('Effect_to_Diseases_progression', models.TextField(max_length=50)),
                ('Materials', models.TextField(max_length=50)),
                ('Information_of_Materials', models.TextField(max_length=50)),
                ('Treatement', models.TextField(max_length=50)),
                ('Binding_site', models.TextField(max_length=50)),
                ('PubChem', models.TextField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
