# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='Binding_site',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='submit',
            name='Date',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='submit',
            name='Effect_to_Diseases_progression',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='submit',
            name='Effect_to_PrP',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='submit',
            name='Information_of_Materials',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='submit',
            name='Materials',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='submit',
            name='PMID',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='submit',
            name='Properties',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='submit',
            name='PubChem',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='submit',
            name='Treatement',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='submit',
            name='Type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='submit',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
